input {
  tcp {
    port  => 5044
    codec => json_lines
  }
}

filter {
  mutate {
    add_field => { "project" => "supply-chain-ams-agent" }
  }
}

output {
  elasticsearch {
    hosts => ["http://supply-chain-ams-elasticsearch:9200"]
    index => "ams-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug { metadata => false } }
}
